Add support for copy pasting in apps running  with executeVanillaTest()
robotools/vanilla pull request #151
Opened 2021-09-16 21:44 UTC by mathieureguer

Add support for copy pasting within `EditText()` in app bundles created by `executeVanillaTest()`

I know `executeVanillaTest()` was created mainly for testing purposes, I hope this is not outside of its scope.

2021-09-17 10:02 UTC, justvanrossum requested changes
This sounds useful, thanks!

Two minor formatting nits, other than that I think this is fine.

2021-09-17 10:02 UTC, justvanrossum commented on Lib/vanilla/test/testTools.py
> +        mainMenu.addItem_(editMenuItem)
Please remove the trailing whitespace

2021-09-17 10:02 UTC, justvanrossum commented on Lib/vanilla/test/testTools.py
> +        AppHelper.runEventLoop()
Please re-add the final newline

2021-09-17 13:23 UTC, typemytype commented
Did you test copy past works outside text related views?

I assume a string selector works on more views instead of a callback to a NSText class

2021-09-17 13:35 UTC, justvanrossum commented
> Did you test copy past works outside text related views?

> I assume a string selector works on more views instead of a callback to a NSText class

I suspect writing `editMenu.addItemWithTitle_action_keyEquivalent_('Cut', NSText.cut_, 'x')` simply does `editMenu.addItemWithTitle_action_keyEquivalent_('Cut', NSText.cut_.selector, 'x')` under the hood, making it 100% equivalent to writing `editMenu.addItemWithTitle_action_keyEquivalent_('Cut', 'cut:', 'x')`. But either way, looking at this again, I think it is better to just write `"cut:"` etc.

2021-09-17 13:36 UTC, justvanrossum commented on Lib/vanilla/test/testTools.py
> +        editMenu.addItemWithTitle_action_keyEquivalent_('Cut', NSText.cut_, 'x')
Please you double quotes (`"`) and write the selectors as strings, such as `"cut:"`, as per main discussion.

2021-09-17 17:52 UTC, mathieureguer commented
Oups, sorry about the sloppy formatting. 
I was confused about the whole selector things when reading the docs, thank you both for clarifying.  
Thanks a lot for the feedback, I'll push an update right away!

2021-09-17 17:59 UTC, justvanrossum requested changes

2021-09-17 17:59 UTC, justvanrossum commented on Lib/vanilla/test/testTools.py
> +from AppKit import NSApplication, NSMenu, NSMenuItem, NSBundle, NSText
The NSText import is now redundant

2021-09-17 18:47 UTC, mathieureguer commented on Lib/vanilla/test/testTools.py
> +from AppKit import NSApplication, NSMenu, NSMenuItem, NSBundle, NSText
🤦️

2021-09-24 14:45 UTC, mathieureguer commented
I am not sure I clicked the right button on GitHub but I _think_ / _hope_ the change requested have been pushed. :)

2021-09-24 14:51 UTC, justvanrossum approved these changes

2021-09-24 14:51 UTC, merged

2021-09-24 14:53 UTC, justvanrossum commented
Yes, thank you! Thanks for the gentle reminder :)